//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrimeInstance
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<double> locationLattitude { get; set; }
        public Nullable<double> locationLongitude { get; set; }
        public string associated_user { get; set; }
    }
}
